//
//  Parameter.swift
//  HiIOS
//
//  Created by liaoya on 2022/7/19.
//

import Foundation

public struct Parameter {
    public static let id                    = "id"
    public static let key                   = "key"
    public static let url                   = "url"
    public static let mac                   = "mac"
    public static let code                  = "code"
    public static let type                  = "type"
    public static let name                  = "name"
    public static let mode                  = "mode"
    public static let query                 = "query"
    public static let value                 = "value"
    public static let state                 = "state"
    public static let title                 = "title"
    public static let index                 = "index"
    public static let model                 = "model"
    public static let style                 = "style"
    public static let error                 = "error"
    public static let active                = "active"
    public static let models                = "models"
    public static let portal                = "portal"
    public static let isDark                = "isDark"
    public static let isList                = "isList"
    public static let userid                = "userid"
    public static let channel               = "channel"
    public static let keyword               = "keyword"
    public static let message               = "message"
    public static let actions               = "actions"
    public static let command               = "command"
    public static let handers               = "handers"
    public static let animated              = "animated"
    public static let pageKey               = "pageKey"
    public static let nickname              = "nickname"
    public static let username              = "username"
    public static let password              = "password"
    public static let priority              = "priority"
    public static let parameter             = "parameter"
    public static let listStyle             = "listStyle"
    public static let entryName             = "entryName"
    public static let timestamp             = "timestamp"
    public static let forwardType           = "forwardType"
    public static let navBarStyle           = "navBarStyle"
    public static let primaryColor          = "primaryColor"
    public static let toastMessage          = "toastMessage"
    public static let toastActivity         = "toastActivity"
    public static let dismissManually       = "dismissManually"
    public static let progressColor         = "progressColor"
    public static let shouldRefresh         = "shouldRefresh"
    public static let shouldLoadMore        = "shouldLoadMore"
    public static let statusBarStyle        = "statusBarStyle"
    public static let backgroundColor       = "backgroundColor"
    public static let backgroundImage       = "backgroundImage"
    public static let transparetNavBar      = "transparetNavBar"
    public static let hidesNavigationBar    = "hidesNavigationBar"
    public static let hidesNavBottomLine    = "hidesNavBottomLine"
    public static let routerUrl             = "_router_url"
    public static let routerHost            = "_router_host"
    public static let routerPath            = "_router_path"
    public static let routerContext         = "_router_context"
    public static let routerObserver        = "_router_observer"
    public static let routerNeedLogin       = "_router_needLogin"
    public static let routerCurrentUser     = "_router_currentUser"
}
