disabled_rules:
    - trailing_whitespace
    - vertical_whitespace

included:
    - IOSTemplate

excluded:
    - Pods
    - IOSTemplate/R.generated.swift

type_name:
    min_length:
        warning: 2
        error: 1
    excluded:
        - T
        - E

identifier_name:
    min_length:
        warning: 2
        error: 1
    excluded:
        - i
        - x
        - y
        - id
