source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

target 'IOSTemplate' do

  pod 'HiIOS', :path => '../../'
  # pod 'HiIOS', '1.0.1'

  # Base
  pod 'RxOptional', '5.0.2'
  pod 'RxSwiftExt', '6.2.1'
  pod 'RxGesture', '4.0.4'
  pod 'RxViewController', '2.0.0'
  pod 'IQKeyboardManagerSwift', '6.5.10'
  pod 'ReusableKit-Hi/RxSwift', '3.0.0-v4'
  pod 'DefaultsKit', '0.2.0'
  pod 'R.swift', '6.1.0'
  pod 'SwiftLint', '0.46.2'
  pod 'Umbrella/Core', '0.12.0'
  pod 'SnapKit', '5.6.0'
  
  # Advanced
  pod 'Toast-Swift', '5.0.1'
  pod 'SwiftEntryKit', '2.0.0'
  
  # Platform
  # pod 'MLeaksFinder', '1.0.0'
  # pod 'FLEX', '3.0.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
	  config.build_settings['CODE_SIGNING_ALLOWED'] ="NO"
    end
  end
  find_and_replace("Pods/FBRetainCycleDetector/FBRetainCycleDetector/Layout/Classes/FBClassStrongLayout.mm",
        "layoutCache[currentClass] = ivars;", "layoutCache[(id<NSCopying>)currentClass] = ivars;")
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      FileUtils.chmod("+w", name)
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
