source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!

target 'HiIOS03Localization' do
  pod 'HiIOS', :path => '../../'
  
  pod 'RxViewController', '2.0.0'
  pod 'R.swift', '6.1.0'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
